import {
  vendorApi,
  useGetSuppliersQuery,
  useGetSupplierQuery,
  useCreateSupplierMutation,
  useUpdateSupplierMutation,
  useGetPurchaseRequestsQuery,
  useCreatePurchaseRequestMutation,
  usePurchaseRequestTransitionMutation,
  useGetPurchaseOrdersQuery,
  useGetPurchaseOrderQuery,
  useCreatePurchaseOrderMutation,
  usePurchaseOrderTransitionMutation,
  useReceivePurchaseOrderMutation,
  useGetGoodsReceiptsQuery,
} from '../vendor/api.js'

export {
  vendorApi,
  useGetSuppliersQuery,
  useGetSupplierQuery,
  useCreateSupplierMutation,
  useUpdateSupplierMutation,
  useGetPurchaseRequestsQuery,
  useCreatePurchaseRequestMutation,
  usePurchaseRequestTransitionMutation,
  useGetPurchaseOrdersQuery,
  useGetPurchaseOrderQuery,
  useCreatePurchaseOrderMutation,
  usePurchaseOrderTransitionMutation,
  useReceivePurchaseOrderMutation,
  useGetGoodsReceiptsQuery,
}