export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PLATFORM_SUPPORT: 'PLATFORM_SUPPORT',

  VENDOR_ADMIN: 'VENDOR_ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_AGENT: 'SALES_AGENT',
  ACCOUNTANT: 'ACCOUNTANT',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  PURCHASING_MANAGER: 'PURCHASING_MANAGER',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  EMPLOYEE: 'EMPLOYEE',
}

export const ROLE_LABELS = {
  SUPER_ADMIN: 'Super Admin',
  PLATFORM_SUPPORT: 'Platform Support',

  VENDOR_ADMIN: 'Vendor Admin',
  SALES_MANAGER: 'Sales Manager',
  SALES_AGENT: 'Sales Agent',
  ACCOUNTANT: 'Accountant',
  INVENTORY_MANAGER: 'Inventory Manager',
  WAREHOUSE_MANAGER: 'Warehouse Manager',
  HR_MANAGER: 'HR Manager',
  PURCHASING_MANAGER: 'Purchasing Manager',
  SUPPORT_AGENT: 'Support Agent',
  EMPLOYEE: 'Employee',
}

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_EDIT: 'CUSTOMER_EDIT',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',
  CUSTOMER_IMPORT: 'CUSTOMER_IMPORT',

  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_EDIT: 'SUPPLIER_EDIT',
  SUPPLIER_DELETE: 'SUPPLIER_DELETE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  TRANSFER_CREATE: 'TRANSFER_CREATE',
  TRANSFER_APPROVE: 'TRANSFER_APPROVE',
  TRANSFER_RECEIVE: 'TRANSFER_RECEIVE',

  WAREHOUSE_MANAGE: 'WAREHOUSE_MANAGE',

  LEAD_VIEW: 'LEAD_VIEW',
  LEAD_CREATE: 'LEAD_CREATE',
  LEAD_EDIT: 'LEAD_EDIT',
  LEAD_DELETE: 'LEAD_DELETE',

  QUOTE_VIEW: 'QUOTE_VIEW',
  QUOTE_CREATE: 'QUOTE_CREATE',
  QUOTE_EDIT: 'QUOTE_EDIT',
  QUOTE_ACTION: 'QUOTE_ACTION',

  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_EDIT: 'ORDER_EDIT',
  ORDER_ACTION: 'ORDER_ACTION',

  INVOICE_VIEW: 'INVOICE_VIEW',
  INVOICE_CREATE: 'INVOICE_CREATE',
  INVOICE_EDIT: 'INVOICE_EDIT',
  INVOICE_DELETE: 'INVOICE_DELETE',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_CREATE: 'PAYMENT_CREATE',

  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_APPROVE: 'PURCHASE_APPROVE',
  PURCHASE_RECEIVE: 'PURCHASE_RECEIVE',

  EXPENSE_VIEW: 'EXPENSE_VIEW',
  EXPENSE_CREATE: 'EXPENSE_CREATE',
  EXPENSE_APPROVE: 'EXPENSE_APPROVE',
  EXPENSE_PROCESS: 'EXPENSE_PROCESS',

  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_EDIT: 'EMPLOYEE_EDIT',
  EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',

  DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',

  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_EDIT: 'ATTENDANCE_EDIT',

  LEAVE_MANAGE: 'LEAVE_MANAGE',
  LEAVE_APPROVE: 'LEAVE_APPROVE',
  LEAVE_CREATE: 'LEAVE_CREATE',

  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_EDIT: 'PROJECT_EDIT',
  PROJECT_DELETE: 'PROJECT_DELETE',

  TASK_MANAGE: 'TASK_MANAGE',

  TICKET_VIEW: 'TICKET_VIEW',
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_EDIT: 'TICKET_EDIT',
  TICKET_ACTION: 'TICKET_ACTION',

  ACCOUNTING_VIEW: 'ACCOUNTING_VIEW',

  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  AUDIT_VIEW: 'AUDIT_VIEW',

  USER_MANAGE: 'USER_MANAGE',
}

export const ALL_PERMISSIONS =
  Object.values(PERMISSIONS)

const all = (...permissions) =>
  permissions

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]:
    ALL_PERMISSIONS,

  [ROLES.PLATFORM_SUPPORT]: all(
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ),

  /*
   * Vendor Admin has complete control
   * over their own vendor tenant.
   */
  [ROLES.VENDOR_ADMIN]:
    ALL_PERMISSIONS,

  [ROLES.SALES_MANAGER]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_EDIT,

    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.QUOTE_CREATE,
    PERMISSIONS.QUOTE_EDIT,
    PERMISSIONS.QUOTE_ACTION,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_EDIT,
    PERMISSIONS.ORDER_ACTION,

    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_CREATE,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_CREATE,
  ),

  [ROLES.SALES_AGENT]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_EDIT,

    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.QUOTE_CREATE,
    PERMISSIONS.QUOTE_EDIT,
    PERMISSIONS.QUOTE_ACTION,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.INVOICE_VIEW,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_CREATE,
  ),

  [ROLES.ACCOUNTANT]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.SUPPLIER_VIEW,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_EDIT,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_CREATE,

    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.ORDER_VIEW,

    PERMISSIONS.PURCHASE_VIEW,

    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_PROCESS,

    PERMISSIONS.ACCOUNTING_VIEW,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ),

  [ROLES.INVENTORY_MANAGER]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.TRANSFER_CREATE,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.TRANSFER_RECEIVE,

    PERMISSIONS.WAREHOUSE_MANAGE,

    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_RECEIVE,

    PERMISSIONS.REPORT_VIEW,
  ),

  [ROLES.WAREHOUSE_MANAGER]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.TRANSFER_CREATE,
    PERMISSIONS.TRANSFER_RECEIVE,

    PERMISSIONS.WAREHOUSE_MANAGE,

    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_RECEIVE,

    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ),

  [ROLES.HR_MANAGER]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.EMPLOYEE_DELETE,

    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_EDIT,

    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.PROJECT_VIEW,
  ),

  [ROLES.PURCHASING_MANAGER]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_EDIT,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_APPROVE,
    PERMISSIONS.PURCHASE_RECEIVE,

    PERMISSIONS.EXPENSE_CREATE,

    PERMISSIONS.REPORT_VIEW,
  ),

  [ROLES.SUPPORT_AGENT]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_EDIT,
    PERMISSIONS.TICKET_ACTION,

    PERMISSIONS.PROJECT_VIEW,
  ),

  [ROLES.EMPLOYEE]: all(
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.EXPENSE_CREATE,

    PERMISSIONS.TICKET_CREATE,
  ),
}