import {
  vendorApi,
  useGetQuotesQuery,
  useGetQuoteQuery,
  useCreateQuoteMutation,
  useUpdateQuoteMutation,
  useQuoteTransitionMutation,
  useConvertQuoteMutation,
  useGetOrdersQuery,
  useGetOrderQuery,
  useCreateOrderMutation,
  useOrderTransitionMutation,
  useGetInvoicesQuery,
  useGetInvoiceQuery,
  useCreateInvoiceMutation,
  useUpdateInvoiceMutation,
  useInvoiceTransitionMutation,
  useRecordInvoicePaymentMutation,
  useGetPaymentsQuery,
} from '../vendor/api.js'

export {
  vendorApi,
  useGetQuotesQuery,
  useGetQuoteQuery,
  useCreateQuoteMutation,
  useUpdateQuoteMutation,
  useQuoteTransitionMutation,
  useConvertQuoteMutation,
  useGetOrdersQuery,
  useGetOrderQuery,
  useCreateOrderMutation,
  useOrderTransitionMutation,
  useGetInvoicesQuery,
  useGetInvoiceQuery,
  useCreateInvoiceMutation,
  useUpdateInvoiceMutation,
  useInvoiceTransitionMutation,
  useRecordInvoicePaymentMutation,
  useGetPaymentsQuery,
}