import {
  vendorApi,
  useGetProductsQuery,
  useGetProductQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useGetCategoriesQuery,
  useCreateCategoryMutation,
  useGetWarehousesQuery,
  useGetWarehouseQuery,
  useGetInventoryQuery,
  useGetInventorySummaryQuery,
  useGetStockAdjustmentsQuery,
  useCreateStockAdjustmentMutation,
  useGetStockTransfersQuery,
  useCreateStockTransferMutation,
  useTransferTransitionMutation,
} from '../vendor/api.js'

export {
  vendorApi,
  useGetProductsQuery,
  useGetProductQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useGetCategoriesQuery,
  useCreateCategoryMutation,
  useGetWarehousesQuery,
  useGetWarehouseQuery,
  useGetInventoryQuery,
  useGetInventorySummaryQuery,
  useGetStockAdjustmentsQuery,
  useCreateStockAdjustmentMutation,
  useGetStockTransfersQuery,
  useCreateStockTransferMutation,
  useTransferTransitionMutation,
}